hw_interface_plugin: "mrs_uav_px4_api/Api"

mavros_timeout: 1.0 # [s]

inputs:
  control_group: false
  attitude_rate: false
  attitude:      true

outputs:
  distance_sensor: true
  gnss: true
  imu: true
  altitude: true
  magnetometer_heading: true
  rc_channels: true
  battery_state: true
  position: true
  orientation: true
  velocity: true
  angular_velocity: true
  odometry: true

services:
  mavros:
    command_long: "mavros/cmd/command"
    mode: "mavros/set_mode"

topics:
  mavros:
    state: "mavros/state"
    gps: "mavros/global_position/global"
    odometry_local: "mavros/local_position/odom"
    distance_sensor: "garmin/range"
    imu: "mavros/imu/data"
    magnetometer_heading: "mavros/global_position/compass_hdg"
    attitude_target: "mavros/setpoint_raw/attitude"
    actuator_control: "mavros/actuator_control"
    rc: "mavros/rc/in"
    altitude: "mavros/altitude"
    battery: "mavros/battery"
